# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Shop_HardMode.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Shop_HardMode(object):
    def setupUi(self, Shop_HardMode):
        Shop_HardMode.setObjectName("Shop_HardMode")
        Shop_HardMode.resize(880, 380)
        Shop_HardMode.setStyleSheet("background-color: #edeef0")
        self.centralwidget = QtWidgets.QWidget(Shop_HardMode)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(365, 10, 151, 51))
        self.label.setStyleSheet("QLabel{\n"
"font-family: Areal;\n"
"padding: 5px;\n"
"border: 5px solid #969393;\n"
"border-radius: 15px;\n"
"font-size: 30px;\n"
"}")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 170, 261, 101))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"font-size: 25px;\n"
"color: white;\n"
"background-color: #969393;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878484;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"font-size: 23px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 90, 261, 101))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"font-size: 25px;\n"
"color: white;\n"
"background-color: #969393;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878484;\n"
"}\n"
"QPushButton:pressed{\n"
"font-size: 23px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 170, 261, 101))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"font-size: 25px;\n"
"color: white;\n"
"background-color: #969393;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878484;\n"
"}\n"
"QPushButton:pressed{\n"
"font-size: 23px;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_money = QtWidgets.QLabel(self.centralwidget)
        self.label_money.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.label_money.setStyleSheet("QLabel{\n"
"font-family: Areal;\n"
"padding: 5px;\n"
"border: 5px solid #969393;\n"
"border-radius: 15px;\n"
"font-size: 20px;\n"
"}")
        self.label_money.setObjectName("label_money")
        self.label_hp = QtWidgets.QLabel(self.centralwidget)
        self.label_hp.setGeometry(QtCore.QRect(10, 60, 141, 41))
        self.label_hp.setStyleSheet("QLabel{\n"
"font-family: Areal;\n"
"padding: 5px;\n"
"border: 5px solid #969393;\n"
"border-radius: 15px;\n"
"font-size: 20px;\n"
"}")
        self.label_hp.setObjectName("label_hp")
        self.label_dmg = QtWidgets.QLabel(self.centralwidget)
        self.label_dmg.setGeometry(QtCore.QRect(10, 110, 141, 41))
        self.label_dmg.setStyleSheet("QLabel{\n"
"font-family: Areal;\n"
"padding: 5px;\n"
"border: 5px solid #969393;\n"
"border-radius: 15px;\n"
"font-size: 20px;\n"
"}")
        self.label_dmg.setObjectName("label_dmg")
        self.label_pay_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_pay_1.setGeometry(QtCore.QRect(10, 290, 261, 41))
        self.label_pay_1.setStyleSheet("QLabel{\n"
"font-family: Areal;\n"
"padding: 5px;\n"
"border: 5px solid #969393;\n"
"border-radius: 15px;\n"
"font-size: 20px;\n"
"}")
        self.label_pay_1.setObjectName("label_pay_1")
        self.label_pay_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_pay_2.setGeometry(QtCore.QRect(610, 290, 261, 41))
        self.label_pay_2.setStyleSheet("QLabel{\n"
"font-family: Areal;\n"
"padding: 5px;\n"
"border: 5px solid #969393;\n"
"border-radius: 15px;\n"
"font-size: 20px;\n"
"}")
        self.label_pay_2.setObjectName("label_pay_2")
        Shop_HardMode.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Shop_HardMode)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 21))
        self.menubar.setObjectName("menubar")
        Shop_HardMode.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Shop_HardMode)
        self.statusbar.setObjectName("statusbar")
        Shop_HardMode.setStatusBar(self.statusbar)

        self.retranslateUi(Shop_HardMode)
        QtCore.QMetaObject.connectSlotsByName(Shop_HardMode)

    def retranslateUi(self, Shop_HardMode):
        _translate = QtCore.QCoreApplication.translate
        Shop_HardMode.setWindowTitle(_translate("Shop_HardMode", "Shop_HardMode"))
        self.label.setText(_translate("Shop_HardMode", "Магазин"))
        self.pushButton.setText(_translate("Shop_HardMode", "Увеличить здоровье"))
        self.pushButton_2.setText(_translate("Shop_HardMode", "К Битве"))
        self.pushButton_3.setText(_translate("Shop_HardMode", "Увеличить урон"))
        self.label_money.setText(_translate("Shop_HardMode", "MONEY - "))
        self.label_hp.setText(_translate("Shop_HardMode", "HP -"))
        self.label_dmg.setText(_translate("Shop_HardMode", "DMG -"))
        self.label_pay_1.setText(_translate("Shop_HardMode", "TextLabel"))
        self.label_pay_2.setText(_translate("Shop_HardMode", "TextLabel"))
