# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start(object):
    def setupUi(self, Start):
        Start.setObjectName("Start")
        Start.resize(1240, 720)
        Start.setStyleSheet("background-color: #edeef0")
        self.centralwidget = QtWidgets.QWidget(Start)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 560, 261, 101))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"font-size: 25px;\n"
"color: white;\n"
"background-color: #969393;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878484;\n"
"}\n"
"QPushButton:pressed{\n"
"font-size: 23px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 560, 261, 101))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"font-size: 25px;\n"
"color: white;\n"
"background-color: #969393;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878484;\n"
"}\n"
"QPushButton:pressed{\n"
"font-size: 23px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(940, 560, 261, 101))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"font-size: 25px;\n"
"color: white;\n"
"background-color: #969393;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878484;\n"
"}\n"
"QPushButton:pressed{\n"
"font-size: 23px;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(407, 30, 426, 70))
        self.label.setStyleSheet("QLabel{\n"
"font-family: Areal;\n"
"padding: 5px;\n"
"border: 5px solid #969393;\n"
"border-radius: 15px;\n"
"font-size: 30px;\n"
"}")
        self.label.setObjectName("label")
        Start.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Start)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 21))
        self.menubar.setObjectName("menubar")
        Start.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Start)
        self.statusbar.setObjectName("statusbar")
        Start.setStatusBar(self.statusbar)

        self.retranslateUi(Start)
        QtCore.QMetaObject.connectSlotsByName(Start)

    def retranslateUi(self, Start):
        _translate = QtCore.QCoreApplication.translate
        Start.setWindowTitle(_translate("Start", "Start"))
        self.pushButton.setText(_translate("Start", "Легкий"))
        self.pushButton_2.setText(_translate("Start", "Средний"))
        self.pushButton_3.setText(_translate("Start", "Сложный"))
        self.label.setText(_translate("Start", "Выберите режим сложности"))
